### ISSUE TITLE
[Feature Request] - Sharding across multiple emulators

### ISSUE THREAD

**Issue by jaredsburrows** [medisafe/run-android-tests#1]

**Comment by sromku** [comment]
@jaredsburrows great idea 🙂. This is something that will be added very soon, since we need to speedup our tests execution. I will share implementation details in a few days. The main idea is to split execution plan to independent groups of tests and commands. Each of the groups can run on different device. This will allow creating dependencies between tests and making sure that group of tests and commands will be executed on the same device if it's necessary.

**Comment by jaredsburrows** [comment]
@sromku Have you looked into [Spoon](https://github.com/square/spoon) and the [Spoon Gradle Plugin](https://github.com/stanfy/spoon-gradle-plugin)? I have used this for sharding many tests with several emulators. Maybe you can leverage this with your setup?

**Comment by sromku** [comment]
@jaredsburrows I saw Spoon project but didn't use it. They are using the common approach of running instrumentations tests and sharding in particular. Eventually they execute something like: `adb shell am instrument -w -e numShards 4 -e shardIndex 1` <- run shard 1/4. But this approach won't allow us to *clear data* between the tests in the same shard. 

Another thing is that execution time of each shard can highly vary. For example, first shard of 4 can take 15 minutes while the second one will take only 2 minutes, just because of nature of tests. So parallelization and time execution is not optimal.

**Comment by jaredsburrows** [comment]
I have used it for when there are around 500+ UI tests. Just a feature suggestion/request. I wanted to see what you think!

**Comment by sromku** [comment]
I think it's a great idea and it will be added very soon ;)

**Comment by sromku** [comment]
**Finally** updated the code and posted a new blog post.

**Sharding and running Android UI tests in parallel. How we improved execution tests time by  40%** - https://medium.com/medisafe-tech-blog/running-android-ui-tests-part-2-15ef08056d94
 
<img src="https://raw.githubusercontent.com/medisafe/run-android-tests/master/assets/following-annotation.png"/>

More details:
- [Parallel — The regular approach vs. push approach](docs/Parallel.md)
- [Grouping following tests](docs/Following.md)

I think you will improve the time execution of 500+ tests if you try the new 'push' approach. I am here for any questions ;)
